# Damn Vulnerable NodeJS Application

version: "2.1"
services:
  app:
    image: appsecco/dvna:sqlite
    ports:
      - 9090:9090

  # mysql-db:
  #   image: mysql:5.7
  #   expose:
  #     - "3306"
  #   env_file:
  #     - ./vars.env
